#!/usr/bin/env bun
/**
 * jose-codegen — the codegen spine.
 *
 * Reads the single source of truth (schema/model/unified-model.json) and emits the
 * generated TypeScript surface consumed across the repo. Today it emits a structural
 * model manifest + id unions; the BufferLayout keystone (Rust + TS byte offsets) is
 * added here in Phase 4 when the SoA buffers exist.
 *
 *   bun run src/index.ts          # write generated files
 *   bun run src/index.ts --check  # fail if regenerating would change anything (CI gate)
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(HERE, "..", "..", "..");
const MODEL_PATH = join(REPO_ROOT, "schema", "model", "unified-model.json");
const OUT_DIR = join(REPO_ROOT, "packages", "model-types", "src", "generated");

// --- model shape (only the fields codegen reads) --------------------------------------
interface Field {
  name: string;
  type?: string;
  unit?: string;
  req?: boolean;
}
interface ModelType {
  id: string;
  stereotype?: string;
  fields?: Field[];
}
interface Layer {
  layerId: string;
  layerName: string;
  pipelineStage?: string;
  types?: ModelType[];
}
interface Model {
  meta: { schema: string; version: string };
  layers: Layer[];
}

// --- deterministic serialization (stable output => meaningful drift diffs) -------------
function stable(value: unknown, indent = 0): string {
  const pad = "  ".repeat(indent);
  const padN = "  ".repeat(indent + 1);
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    const items = value.map((v) => padN + stable(v, indent + 1));
    return `[\n${items.join(",\n")}\n${pad}]`;
  }
  const keys = Object.keys(value as Record<string, unknown>).sort();
  if (keys.length === 0) return "{}";
  const entries = keys.map(
    (k) => `${padN}${JSON.stringify(k)}: ${stable((value as Record<string, unknown>)[k], indent + 1)}`,
  );
  return `{\n${entries.join(",\n")}\n${pad}}`;
}

const sortedUnique = (xs: string[]): string[] => [...new Set(xs)].sort();
const unionType = (name: string, values: string[]): string =>
  values.length === 0
    ? `export type ${name} = never;`
    : `export type ${name} =\n${values.map((v) => `  | ${JSON.stringify(v)}`).join("\n")};`;

// --- generation -----------------------------------------------------------------------
function generate(model: Model): Record<string, string> {
  const banner =
    `// @generated by tooling/codegen from schema/model/unified-model.json — do not edit.\n` +
    `// Run \`bun run codegen\` to regenerate. Model version: ${model.meta.version}.\n`;

  const layerIds = sortedUnique(model.layers.map((l) => l.layerId));
  const stages = sortedUnique(model.layers.map((l) => l.pipelineStage ?? "").filter(Boolean));
  const typeIds = sortedUnique(model.layers.flatMap((l) => (l.types ?? []).map((t) => t.id)));
  const stereotypes = sortedUnique(
    model.layers.flatMap((l) => (l.types ?? []).map((t) => t.stereotype ?? "").filter(Boolean)),
  );

  const manifest = {
    schema: model.meta.schema,
    version: model.meta.version,
    layers: model.layers.map((l) => ({
      layerId: l.layerId,
      layerName: l.layerName,
      pipelineStage: l.pipelineStage ?? null,
      types: (l.types ?? []).map((t) => ({
        id: t.id,
        stereotype: t.stereotype ?? null,
        fields: (t.fields ?? []).map((f) => ({
          name: f.name,
          type: f.type ?? null,
          unit: f.unit ?? null,
          req: f.req ?? false,
        })),
      })),
    })),
  };

  const ids =
    banner +
    "\n" +
    unionType("LayerId", layerIds) +
    "\n\n" +
    unionType("PipelineStage", stages) +
    "\n\n" +
    unionType("Stereotype", stereotypes) +
    "\n\n" +
    unionType("TypeId", typeIds) +
    "\n\n" +
    `export const LAYER_IDS: readonly LayerId[] = ${stable(layerIds)} as const;\n` +
    `export const TYPE_IDS: readonly TypeId[] = ${stable(typeIds)} as const;\n`;

  const manifestTs =
    banner +
    `\nimport type { LayerId, PipelineStage, Stereotype, TypeId } from "./ids";\n` +
    `\nexport interface ModelField {\n` +
    `  readonly name: string;\n` +
    `  readonly type: string | null;\n` +
    `  readonly unit: string | null;\n` +
    `  readonly req: boolean;\n` +
    `}\n` +
    `export interface ModelTypeDef {\n` +
    `  readonly id: TypeId;\n` +
    `  readonly stereotype: Stereotype | null;\n` +
    `  readonly fields: readonly ModelField[];\n` +
    `}\n` +
    `export interface ModelLayer {\n` +
    `  readonly layerId: LayerId;\n` +
    `  readonly layerName: string;\n` +
    `  readonly pipelineStage: PipelineStage | null;\n` +
    `  readonly types: readonly ModelTypeDef[];\n` +
    `}\n` +
    `export interface ModelManifest {\n` +
    `  readonly schema: string;\n` +
    `  readonly version: string;\n` +
    `  readonly layers: readonly ModelLayer[];\n` +
    `}\n` +
    `\nexport const MODEL_MANIFEST: ModelManifest = ${stable(manifest)};\n`;

  const index =
    banner +
    `\nexport const MODEL_VERSION = ${JSON.stringify(model.meta.version)} as const;\n` +
    `export * from "./ids";\n` +
    `export * from "./manifest";\n`;

  return { "ids.ts": ids, "manifest.ts": manifestTs, "index.ts": index };
}

// --- driver ---------------------------------------------------------------------------
function main(): void {
  const check = process.argv.includes("--check");
  if (!existsSync(MODEL_PATH)) {
    console.error(`codegen: model not found at ${relative(REPO_ROOT, MODEL_PATH)}`);
    process.exit(1);
  }
  const model = JSON.parse(readFileSync(MODEL_PATH, "utf8")) as Model;
  const files = generate(model);

  if (check) {
    const drifted: string[] = [];
    for (const [name, content] of Object.entries(files)) {
      const path = join(OUT_DIR, name);
      const current = existsSync(path) ? readFileSync(path, "utf8") : null;
      if (current !== content) drifted.push(relative(REPO_ROOT, path));
    }
    if (drifted.length > 0) {
      console.error("codegen: generated files are out of date — run `bun run codegen`:");
      for (const f of drifted) console.error(`  - ${f}`);
      process.exit(1);
    }
    console.log(`codegen: up to date (${Object.keys(files).length} files, model v${model.meta.version})`);
    return;
  }

  mkdirSync(OUT_DIR, { recursive: true });
  for (const [name, content] of Object.entries(files)) {
    writeFileSync(join(OUT_DIR, name), content);
  }
  console.log(
    `codegen: wrote ${Object.keys(files).length} files to ${relative(REPO_ROOT, OUT_DIR)} (model v${model.meta.version})`,
  );
}

main();
