#!/usr/bin/env bun
/**
 * jose-codegen — the codegen spine.
 *
 * Reads the single source of truth (schema/model/) and emits the generated surface consumed
 * across the repo:
 *   - the structural model manifest + id unions     -> packages/model-types/src/generated/*.ts
 *   - the SoA `BufferLayout` keystone (byte offsets) -> packages/model-types/src/generated/layout.ts (TS reader side)
 *                                                    -> crates/bim-core/src/generated/layout.rs    (Rust writer side)
 *
 * The BufferLayout is the load-bearing tidiness mechanism: the Rust worker (writer) and the JS
 * render mirror (reader) load the *identical* generated offset table, so the two sides provably
 * cannot drift. CI runs `--check` and fails on any uncommitted delta.
 *
 *   bun run src/index.ts          # write generated files
 *   bun run src/index.ts --check  # fail if regenerating would change anything (CI gate)
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(HERE, "..", "..", "..");
const MODEL_PATH = join(REPO_ROOT, "schema", "model", "unified-model.json");
const LAYOUTS_PATH = join(REPO_ROOT, "schema", "model", "buffer-layouts.json");
const TS_OUT_DIR = join(REPO_ROOT, "packages", "model-types", "src", "generated");
const RUST_LAYOUT_PATH = join(REPO_ROOT, "crates", "bim-core", "src", "generated", "layout.rs");

// --- model shape (only the fields codegen reads) --------------------------------------
interface Field {
  name: string;
  type?: string;
  unit?: string;
  req?: boolean;
}
interface ModelType {
  id: string;
  stereotype?: string;
  fields?: Field[];
}
interface Layer {
  layerId: string;
  layerName: string;
  pipelineStage?: string;
  types?: ModelType[];
}
interface Model {
  meta: { schema: string; version: string };
  layers: Layer[];
}

// --- buffer-layout shape --------------------------------------------------------------
type ElementType = "i32" | "u32" | "i64" | "u64" | "f32" | "f64" | "u8";
type FieldClass = "linearTick" | "derivedReal" | "flag" | "id" | "key" | "dir";
interface ColumnSpec {
  field: string;
  elementType: ElementType;
  fieldClass: FieldClass;
}
interface BufferSpec {
  domainType: string;
  capacity: number;
  columns: ColumnSpec[];
  roles?: string[];
}
interface LayoutsSpec {
  schemaVersion: string;
  alignment: number;
  buffers: BufferSpec[];
}

// Byte width and JS typed-array kind per element type — the i32→Int32Array contract.
const WIDTH: Record<ElementType, number> = { i32: 4, u32: 4, i64: 8, u64: 8, f32: 4, f64: 8, u8: 1 };
const ARRAY_KIND: Record<ElementType, string> = {
  i32: "Int32Array",
  u32: "Uint32Array",
  i64: "BigInt64Array",
  u64: "BigUint64Array",
  f32: "Float32Array",
  f64: "Float64Array",
  u8: "Uint8Array",
};

// --- deterministic serialization (stable output => meaningful drift diffs) -------------
function stable(value: unknown, indent = 0): string {
  const pad = "  ".repeat(indent);
  const padN = "  ".repeat(indent + 1);
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    const items = value.map((v) => padN + stable(v, indent + 1));
    return `[\n${items.join(",\n")}\n${pad}]`;
  }
  const keys = Object.keys(value as Record<string, unknown>).sort();
  if (keys.length === 0) return "{}";
  const entries = keys.map(
    (k) => `${padN}${JSON.stringify(k)}: ${stable((value as Record<string, unknown>)[k], indent + 1)}`,
  );
  return `{\n${entries.join(",\n")}\n${pad}}`;
}

const sortedUnique = (xs: string[]): string[] => [...new Set(xs)].sort();
const unionType = (name: string, values: string[]): string =>
  values.length === 0
    ? `export type ${name} = never;`
    : `export type ${name} =\n${values.map((v) => `  | ${JSON.stringify(v)}`).join("\n")};`;

// FNV-1a (32-bit) over a canonical string — a stable digest both generated files carry so the
// Rust build and the JS build can assert layout equality at startup.
function fnv1a(s: string): string {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return (h >>> 0).toString(16).padStart(8, "0");
}

const alignUp = (n: number, a: number): number => Math.ceil(n / a) * a;

// --- layout computation (pure column-major, generated byte offsets) -------------------
interface ComputedColumn {
  field: string;
  elementType: ElementType;
  fieldClass: FieldClass;
  arrayKind: string;
  byteOffset: number;
  stride: number;
}
interface ComputedBuffer {
  domainType: string;
  capacity: number;
  elementStride: number;
  bufferBytes: number;
  columns: ComputedColumn[];
  roles: string[];
}

function computeBuffer(spec: BufferSpec, alignment: number): ComputedBuffer {
  let offset = 0;
  let elementStride = 0;
  const columns: ComputedColumn[] = spec.columns.map((c) => {
    const stride = WIDTH[c.elementType];
    offset = alignUp(offset, alignment);
    const byteOffset = offset;
    offset += spec.capacity * stride;
    elementStride += stride;
    return {
      field: c.field,
      elementType: c.elementType,
      fieldClass: c.fieldClass,
      arrayKind: ARRAY_KIND[c.elementType],
      byteOffset,
      stride,
    };
  });
  return {
    domainType: spec.domainType,
    capacity: spec.capacity,
    elementStride,
    bufferBytes: alignUp(offset, alignment),
    columns,
    roles: spec.roles ?? [],
  };
}

// --- a generated file target --------------------------------------------------------------
interface Target {
  path: string;
  content: string;
}

// --- model-types: ids + manifest + index ----------------------------------------------
function generateModelTypes(model: Model, banner: string): Record<string, string> {
  const layerIds = sortedUnique(model.layers.map((l) => l.layerId));
  const stages = sortedUnique(model.layers.map((l) => l.pipelineStage ?? "").filter(Boolean));
  const typeIds = sortedUnique(model.layers.flatMap((l) => (l.types ?? []).map((t) => t.id)));
  const stereotypes = sortedUnique(
    model.layers.flatMap((l) => (l.types ?? []).map((t) => t.stereotype ?? "").filter(Boolean)),
  );

  const manifest = {
    schema: model.meta.schema,
    version: model.meta.version,
    layers: model.layers.map((l) => ({
      layerId: l.layerId,
      layerName: l.layerName,
      pipelineStage: l.pipelineStage ?? null,
      types: (l.types ?? []).map((t) => ({
        id: t.id,
        stereotype: t.stereotype ?? null,
        fields: (t.fields ?? []).map((f) => ({
          name: f.name,
          type: f.type ?? null,
          unit: f.unit ?? null,
          req: f.req ?? false,
        })),
      })),
    })),
  };

  const ids =
    banner +
    "\n" +
    unionType("LayerId", layerIds) +
    "\n\n" +
    unionType("PipelineStage", stages) +
    "\n\n" +
    unionType("Stereotype", stereotypes) +
    "\n\n" +
    unionType("TypeId", typeIds) +
    "\n\n" +
    `export const LAYER_IDS: readonly LayerId[] = ${stable(layerIds)} as const;\n` +
    `export const TYPE_IDS: readonly TypeId[] = ${stable(typeIds)} as const;\n`;

  const manifestTs =
    banner +
    `\nimport type { LayerId, PipelineStage, Stereotype, TypeId } from "./ids";\n` +
    `\nexport interface ModelField {\n` +
    `  readonly name: string;\n` +
    `  readonly type: string | null;\n` +
    `  readonly unit: string | null;\n` +
    `  readonly req: boolean;\n` +
    `}\n` +
    `export interface ModelTypeDef {\n` +
    `  readonly id: TypeId;\n` +
    `  readonly stereotype: Stereotype | null;\n` +
    `  readonly fields: readonly ModelField[];\n` +
    `}\n` +
    `export interface ModelLayer {\n` +
    `  readonly layerId: LayerId;\n` +
    `  readonly layerName: string;\n` +
    `  readonly pipelineStage: PipelineStage | null;\n` +
    `  readonly types: readonly ModelTypeDef[];\n` +
    `}\n` +
    `export interface ModelManifest {\n` +
    `  readonly schema: string;\n` +
    `  readonly version: string;\n` +
    `  readonly layers: readonly ModelLayer[];\n` +
    `}\n` +
    `\nexport const MODEL_MANIFEST: ModelManifest = ${stable(manifest)};\n`;

  const index =
    banner +
    `\nexport const MODEL_VERSION = ${JSON.stringify(model.meta.version)} as const;\n` +
    `export * from "./ids";\n` +
    `export * from "./manifest";\n` +
    `export * from "./layout";\n`;

  return { "ids.ts": ids, "manifest.ts": manifestTs, "index.ts": index };
}

// --- the BufferLayout keystone: TS reader side ----------------------------------------
function generateLayoutTs(buffers: ComputedBuffer[], alignment: number, hash: string, banner: string): string {
  const byType = Object.fromEntries(buffers.map((b) => [b.domainType, b]));
  return (
    banner +
    `\n` +
    `/** Digest of the generated layout tables; the Rust writer carries the same constant so a\n` +
    ` * schema/codegen mismatch is caught at startup, not as silent buffer corruption. */\n` +
    `export const LAYOUT_HASH = ${JSON.stringify(hash)} as const;\n` +
    `\n/** Target byte alignment for every column start. */\n` +
    `export const LAYOUT_ALIGNMENT = ${alignment} as const;\n` +
    `\nexport type ColumnElementType = "i32" | "u32" | "i64" | "u64" | "f32" | "f64" | "u8";\n` +
    `export type ColumnFieldClass = "linearTick" | "derivedReal" | "flag" | "id" | "key" | "dir";\n` +
    `export type TypedArrayKind =\n` +
    `  | "Int32Array"\n` +
    `  | "Uint32Array"\n` +
    `  | "Float32Array"\n` +
    `  | "Float64Array"\n` +
    `  | "Uint8Array"\n` +
    `  | "BigInt64Array"\n` +
    `  | "BigUint64Array";\n` +
    `\nexport interface BufferColumn {\n` +
    `  readonly field: string;\n` +
    `  readonly elementType: ColumnElementType;\n` +
    `  readonly fieldClass: ColumnFieldClass;\n` +
    `  readonly arrayKind: TypedArrayKind;\n` +
    `  /** Byte offset of element[0] from the buffer base. Generated, never hand-written. */\n` +
    `  readonly byteOffset: number;\n` +
    `  /** Bytes between consecutive elements in this column (the element width). */\n` +
    `  readonly stride: number;\n` +
    `}\n` +
    `export interface BufferLayout {\n` +
    `  readonly domainType: string;\n` +
    `  /** Rows allocated before a grow is required. */\n` +
    `  readonly capacity: number;\n` +
    `  /** Total bytes per logical element across all columns. */\n` +
    `  readonly elementStride: number;\n` +
    `  /** Total bytes of the column block (capacity rows of every column). */\n` +
    `  readonly bufferBytes: number;\n` +
    `  readonly columns: readonly BufferColumn[];\n` +
    `  /** Vocabulary indexed by an \`id\`-class roleId column, when the buffer has one. */\n` +
    `  readonly roles: readonly string[];\n` +
    `}\n` +
    `\nexport const BUFFER_LAYOUTS = ${stable(byType)} as const satisfies Record<string, BufferLayout>;\n`
  );
}

// --- the BufferLayout keystone: Rust writer side --------------------------------------
const SCREAMING = (s: string): string => s.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();

function generateLayoutRs(buffers: ComputedBuffer[], alignment: number, hash: string, version: string): string {
  const lines: string[] = [];
  lines.push(`// @generated by tooling/codegen from schema/model/buffer-layouts.json — do not edit.`);
  lines.push(`// Run \`bun run codegen\` to regenerate. Model version: ${version}.`);
  lines.push(`//`);
  lines.push(`// The SoA BufferLayout keystone: the byte offsets the Rust worker (writer) and the JS`);
  lines.push(`// render mirror (reader) both load, so the two sides provably cannot drift.`);
  lines.push(``);
  lines.push(`/// Digest of the generated layout tables; the JS reader carries the same constant so a`);
  lines.push(`/// schema/codegen mismatch is caught at startup, not as silent buffer corruption.`);
  lines.push(`pub const LAYOUT_HASH: &str = "${hash}";`);
  lines.push(``);
  lines.push(`/// Target byte alignment for every column start.`);
  lines.push(`pub const ALIGNMENT: usize = ${alignment};`);

  for (const b of buffers) {
    const mod = SCREAMING(b.domainType).toLowerCase();
    lines.push(``);
    lines.push(`/// Layout of the \`${b.domainType}\` SoA buffer (pure column-major).`);
    lines.push(`pub mod ${mod} {`);
    lines.push(`    /// Domain type this buffer mirrors.`);
    lines.push(`    pub const DOMAIN_TYPE: &str = "${b.domainType}";`);
    lines.push(`    /// Rows allocated before a grow is required.`);
    lines.push(`    pub const CAPACITY: usize = ${b.capacity};`);
    lines.push(`    /// Total bytes per logical element across all columns.`);
    lines.push(`    pub const ELEMENT_STRIDE: usize = ${b.elementStride};`);
    lines.push(`    /// Total bytes of the column block (CAPACITY rows of every column).`);
    lines.push(`    pub const BUFFER_BYTES: usize = ${b.bufferBytes};`);
    lines.push(``);
    lines.push(`    /// Byte offset of element[0] for each column, from the buffer base. Generated.`);
    for (const c of b.columns) {
      lines.push(`    pub const ${SCREAMING(c.field)}_OFFSET: usize = ${c.byteOffset};`);
    }
    if (b.roles.length > 0) {
      lines.push(``);
      lines.push(`    /// Framing roles, indexed by the \`roleId\` column.`);
      lines.push(`    #[rustfmt::skip]`); // codegen owns this array's one-per-line shape
      lines.push(`    pub const ROLES: [&str; ${b.roles.length}] = [`);
      for (const r of b.roles) lines.push(`        "${r}",`);
      lines.push(`    ];`);
      lines.push(``);
      lines.push(`    /// Resolve a role string to the stable id stored in the \`roleId\` column.`);
      lines.push(`    pub fn role_id(role: &str) -> Option<u32> {`);
      lines.push(`        ROLES.iter().position(|r| *r == role).map(|i| i as u32)`);
      lines.push(`    }`);
    }
    lines.push(`}`);
  }
  lines.push(``);
  return lines.join("\n");
}

// --- driver ---------------------------------------------------------------------------
function buildTargets(model: Model, spec: LayoutsSpec): Target[] {
  const banner =
    `// @generated by tooling/codegen from schema/model/ — do not edit.\n` +
    `// Run \`bun run codegen\` to regenerate. Model version: ${model.meta.version}.\n`;

  const buffers = spec.buffers.map((b) => computeBuffer(b, spec.alignment));
  // Hash a canonical view of the computed layout — offsets included — so any byte-offset change
  // bumps the digest the two language builds compare.
  const hash = "layout-" + fnv1a(stable({ schemaVersion: spec.schemaVersion, alignment: spec.alignment, buffers }));

  const tsFiles = generateModelTypes(model, banner);
  tsFiles["layout.ts"] = generateLayoutTs(buffers, spec.alignment, hash, banner);

  const targets: Target[] = Object.entries(tsFiles).map(([name, content]) => ({
    path: join(TS_OUT_DIR, name),
    content,
  }));
  targets.push({ path: RUST_LAYOUT_PATH, content: generateLayoutRs(buffers, spec.alignment, hash, model.meta.version) });
  return targets;
}

function main(): void {
  const check = process.argv.includes("--check");
  for (const [label, path] of [
    ["model", MODEL_PATH],
    ["buffer-layouts", LAYOUTS_PATH],
  ] as const) {
    if (!existsSync(path)) {
      console.error(`codegen: ${label} not found at ${relative(REPO_ROOT, path)}`);
      process.exit(1);
    }
  }
  const model = JSON.parse(readFileSync(MODEL_PATH, "utf8")) as Model;
  const layouts = JSON.parse(readFileSync(LAYOUTS_PATH, "utf8")) as LayoutsSpec;
  const targets = buildTargets(model, layouts);

  if (check) {
    const drifted: string[] = [];
    for (const t of targets) {
      const current = existsSync(t.path) ? readFileSync(t.path, "utf8") : null;
      if (current !== t.content) drifted.push(relative(REPO_ROOT, t.path));
    }
    if (drifted.length > 0) {
      console.error("codegen: generated files are out of date — run `bun run codegen`:");
      for (const f of drifted) console.error(`  - ${f}`);
      process.exit(1);
    }
    console.log(`codegen: up to date (${targets.length} files, model v${model.meta.version})`);
    return;
  }

  for (const t of targets) {
    mkdirSync(dirname(t.path), { recursive: true });
    writeFileSync(t.path, t.content);
  }
  console.log(`codegen: wrote ${targets.length} files (model v${model.meta.version})`);
}

main();
