//! The `MemberPlacement` SoA column store — the canonical buffer the Rust worker *writes* and the
//! JS render mirror *reads*, byte-for-byte, through the generated [`layout`](crate::layout).
//!
//! Pure column-major: each column is `CAPACITY` contiguous elements at its generated byte offset,
//! so a JS typed-array view (`Int32Array`/`Uint32Array`) cuts over exactly one column with zero
//! copy. Linear values are little-endian integer ticks regardless of host, matching how the wasm
//! reader (always little-endian) interprets the same bytes.

use crate::layout::member_placement as L;

/// Nominal section draw width — a dressed 1.5in face = 48 ticks. Stored per row so the width can
/// vary by spec later without touching the layout.
pub const NOMINAL_WIDTH: i32 = 48;

/// One framing member's render row: a segment (start → end), a draw width, and a role id. All
/// linear values are integer ticks (1/32in); coordinates are wall-local elevation (x along the
/// baseline, z up).
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct MemberRow {
    pub x0: i32,
    pub y0: i32,
    pub z0: i32,
    pub x1: i32,
    pub y1: i32,
    pub z1: i32,
    pub width: i32,
    pub role_id: u32,
}

/// A struct-of-arrays column store for the `MemberPlacement` buffer, laid out exactly as the
/// generated [`layout`](crate::layout) table says. Owns its backing bytes; the worker is the only
/// writer, the mirror a read-only viewer.
#[derive(Clone, Debug)]
pub struct MemberBuffer {
    bytes: Vec<u8>,
    len: usize,
}

impl Default for MemberBuffer {
    fn default() -> Self {
        MemberBuffer::new()
    }
}

impl MemberBuffer {
    /// A zeroed buffer sized for the generated column block (`CAPACITY` rows of every column).
    pub fn new() -> MemberBuffer {
        MemberBuffer {
            bytes: vec![0u8; L::BUFFER_BYTES],
            len: 0,
        }
    }

    /// Number of live rows written.
    pub fn len(&self) -> usize {
        self.len
    }

    /// Whether no rows have been written.
    pub fn is_empty(&self) -> bool {
        self.len == 0
    }

    /// Rows the buffer can hold before a grow is required.
    pub fn capacity(&self) -> usize {
        L::CAPACITY
    }

    /// The raw column-block bytes — handed to JS as the read-only render mirror.
    pub fn as_bytes(&self) -> &[u8] {
        &self.bytes
    }

    /// Drop all rows (the recompute rewrites from scratch). Bytes are left as-is; `len` bounds
    /// what the reader walks, so stale tail bytes are never read.
    pub fn clear(&mut self) {
        self.len = 0;
    }

    /// Append one member row at the next index. Returns `false` (dropping the row) when the
    /// buffer is full — the grow seam (realloc to a larger `CAPACITY`) lands with persistence in
    /// Phase 5.
    pub fn push(&mut self, row: MemberRow) -> bool {
        if self.len >= L::CAPACITY {
            return false;
        }
        let i = self.len;
        self.write_i32(L::X0_OFFSET, i, row.x0);
        self.write_i32(L::Y0_OFFSET, i, row.y0);
        self.write_i32(L::Z0_OFFSET, i, row.z0);
        self.write_i32(L::X1_OFFSET, i, row.x1);
        self.write_i32(L::Y1_OFFSET, i, row.y1);
        self.write_i32(L::Z1_OFFSET, i, row.z1);
        self.write_i32(L::WIDTH_OFFSET, i, row.width);
        self.write_u32(L::ROLE_ID_OFFSET, i, row.role_id);
        self.len += 1;
        true
    }

    fn write_i32(&mut self, col_offset: usize, index: usize, value: i32) {
        let at = col_offset + index * 4;
        self.bytes[at..at + 4].copy_from_slice(&value.to_le_bytes());
    }

    fn write_u32(&mut self, col_offset: usize, index: usize, value: u32) {
        let at = col_offset + index * 4;
        self.bytes[at..at + 4].copy_from_slice(&value.to_le_bytes());
    }

    /// Read one i32 column element back (test/inspection helper — JS reads the same bytes).
    #[cfg(test)]
    fn read_i32(&self, col_offset: usize, index: usize) -> i32 {
        let at = col_offset + index * 4;
        i32::from_le_bytes(self.bytes[at..at + 4].try_into().unwrap())
    }

    /// Read one u32 column element back.
    #[cfg(test)]
    fn read_u32(&self, col_offset: usize, index: usize) -> u32 {
        let at = col_offset + index * 4;
        u32::from_le_bytes(self.bytes[at..at + 4].try_into().unwrap())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn row(n: i32) -> MemberRow {
        MemberRow {
            x0: n,
            y0: n + 1,
            z0: n + 2,
            x1: n + 3,
            y1: n + 4,
            z1: n + 5,
            width: NOMINAL_WIDTH,
            role_id: 1,
        }
    }

    #[test]
    fn columns_are_written_at_generated_offsets() {
        let mut b = MemberBuffer::new();
        assert!(b.is_empty());
        assert!(b.push(row(100)));
        assert!(b.push(row(200)));
        assert_eq!(b.len(), 2);

        // Column-major: row i of a column sits at COL_OFFSET + i*4, independent of other columns.
        assert_eq!(b.read_i32(L::X0_OFFSET, 0), 100);
        assert_eq!(b.read_i32(L::X0_OFFSET, 1), 200);
        assert_eq!(b.read_i32(L::Z1_OFFSET, 0), 105);
        assert_eq!(b.read_i32(L::Z1_OFFSET, 1), 205);
        assert_eq!(b.read_i32(L::WIDTH_OFFSET, 1), NOMINAL_WIDTH);
        assert_eq!(b.read_u32(L::ROLE_ID_OFFSET, 1), 1);
    }

    #[test]
    fn bytes_span_the_whole_generated_block() {
        let b = MemberBuffer::new();
        assert_eq!(b.as_bytes().len(), L::BUFFER_BYTES);
        assert_eq!(b.capacity(), L::CAPACITY);
    }

    #[test]
    fn clear_resets_len_without_reading_stale_tail() {
        let mut b = MemberBuffer::new();
        b.push(row(7));
        b.clear();
        assert_eq!(b.len(), 0);
        assert!(b.is_empty());
    }
}
