import { expect, test } from "bun:test";
import { BUFFER_LAYOUTS, LAYOUT_HASH } from "@jose/model-types";
import {
  assertLayout,
  FootprintMirror,
  MEMBER_ROLES,
  MemberMirror,
  VolumeMirror,
} from "./index";

const L = BUFFER_LAYOUTS.MemberPlacement;

/** Encode rows into a SoA block exactly as the Rust writer does: pure column-major, little-endian,
 *  at the *generated* byte offsets. If the reader and this writer agree, the keystone holds. */
function encode(rows: Record<string, number>[]): ArrayBuffer {
  const buffer = new ArrayBuffer(L.bufferBytes);
  const view = new DataView(buffer);
  rows.forEach((row, i) => {
    for (const col of L.columns) {
      const at = col.byteOffset + i * col.stride;
      const value = row[col.field] ?? 0;
      if (col.arrayKind === "Uint32Array") {
        view.setUint32(at, value, true);
      } else {
        view.setInt32(at, value, true);
      }
    }
  });
  return buffer;
}

test("decodes rows written at the generated column offsets", () => {
  const studId = MEMBER_ROLES.indexOf("stud");
  const plateId = MEMBER_ROLES.indexOf("plate");
  const buffer = encode([
    { x0: 0, y0: 0, z0: 48, x1: 0, y1: 0, z1: 2976, width: 48, roleId: studId },
    { x0: 0, y0: 0, z0: 0, x1: 3840, y1: 0, z1: 0, width: 48, roleId: plateId },
  ]);

  const mirror = new MemberMirror(buffer, 2);
  expect(mirror.count).toBe(2);

  const stud = mirror.row(0);
  expect(stud.role).toBe("stud");
  expect(stud.z1 - stud.z0).toBe(2928); // extends up the wall
  expect(stud.x0).toBe(stud.x1);

  const plate = mirror.row(1);
  expect(plate.role).toBe("plate");
  expect(plate.x1 - plate.x0).toBe(3840); // runs along the baseline
  expect(plate.z0).toBe(plate.z1);

  expect(mirror.rows()).toHaveLength(2);
});

test("count bounds the rows read — stale tail bytes are ignored", () => {
  const buffer = encode([
    { x0: 1, roleId: 0 },
    { x0: 2, roleId: 0 },
    { x0: 3, roleId: 0 },
  ]);
  // Worker reported only 1 live row even though 3 were encoded.
  const mirror = new MemberMirror(buffer, 1);
  expect(mirror.rows()).toHaveLength(1);
  expect(() => mirror.row(1)).toThrow();
});

test("views are zero-copy — mutating the backing buffer shows through", () => {
  const buffer = encode([{ x0: 10, roleId: 0 }]);
  const mirror = new MemberMirror(buffer, 1);
  expect(mirror.row(0).x0).toBe(10);
  new DataView(buffer).setInt32(L.columns[0]!.byteOffset, 999, true);
  expect(mirror.row(0).x0).toBe(999); // same bytes, no copy
});

test("rejects a buffer that is too small for the layout", () => {
  expect(() => new MemberMirror(new ArrayBuffer(16), 0)).toThrow();
});

test("assertLayout guards the keystone hash", () => {
  expect(() => assertLayout(LAYOUT_HASH)).not.toThrow();
  expect(() => assertLayout("layout-deadbeef")).toThrow(/mismatch/);
});

const FP = BUFFER_LAYOUTS.Footprint;
const VOL = BUFFER_LAYOUTS.Volume;

/** Encode rows into any SoA layout exactly as the Rust writer does: pure column-major, LE, at the
 *  generated byte offsets. Shared by the footprint and volume mirror tests. */
function encodeInto(
  layout: typeof FP | typeof VOL,
  rows: Record<string, number>[]
): ArrayBuffer {
  const buffer = new ArrayBuffer(layout.bufferBytes);
  const view = new DataView(buffer);
  rows.forEach((row, i) => {
    for (const col of layout.columns) {
      const at = col.byteOffset + i * col.stride;
      const value = row[col.field] ?? 0;
      if (col.arrayKind === "Uint32Array") {
        view.setUint32(at, value, true);
      } else {
        view.setInt32(at, value, true);
      }
    }
  });
  return buffer;
}

test("FootprintMirror decodes vertex columns at the generated offsets", () => {
  // A 10ft x 8ft rectangle ring (ticks: 1ft = 384), all in space 0.
  const buffer = encodeInto(FP, [
    { x: 0, y: 0, spaceId: 0 },
    { x: 3840, y: 0, spaceId: 0 },
    { x: 3840, y: 3072, spaceId: 0 },
    { x: 0, y: 3072, spaceId: 0 },
  ]);

  const mirror = new FootprintMirror(buffer, 4);
  expect(mirror.count).toBe(4);

  expect(mirror.vertex(0)).toEqual({ x: 0, y: 0, spaceId: 0 });
  expect(mirror.vertex(2)).toEqual({ x: 3840, y: 3072, spaceId: 0 });
  expect(mirror.vertices()).toHaveLength(4);
  expect(() => mirror.vertex(4)).toThrow();
});

test("FootprintMirror count bounds the rows — stale tail bytes are ignored", () => {
  const buffer = encodeInto(FP, [
    { x: 1, y: 1 },
    { x: 2, y: 2 },
    { x: 3, y: 3 },
  ]);
  const mirror = new FootprintMirror(buffer, 1);
  expect(mirror.vertices()).toHaveLength(1);
  expect(mirror.vertices()[0]).toEqual({ x: 1, y: 1, spaceId: 0 });
});

test("FootprintMirror views are zero-copy — buffer mutation shows through", () => {
  const buffer = encodeInto(FP, [{ x: 10, y: 20 }]);
  const mirror = new FootprintMirror(buffer, 1);
  expect(mirror.vertex(0).x).toBe(10);
  new DataView(buffer).setInt32(FP.columns[0]!.byteOffset, 999, true);
  expect(mirror.vertex(0).x).toBe(999);
});

test("FootprintMirror rejects a buffer too small for the layout", () => {
  expect(() => new FootprintMirror(new ArrayBuffer(16), 0)).toThrow();
});

test("VolumeMirror decodes volumeId/spaceId/height at the generated offsets", () => {
  const buffer = encodeInto(VOL, [
    { volumeId: 7, spaceId: 0, height: 8 * 384 },
    { volumeId: 8, spaceId: 1, height: 9 * 384 },
  ]);

  const mirror = new VolumeMirror(buffer, 2);
  expect(mirror.count).toBe(2);
  expect(mirror.row(0)).toEqual({ volumeId: 7, spaceId: 0, height: 3072 });
  expect(mirror.row(1)).toEqual({ volumeId: 8, spaceId: 1, height: 3456 });
  expect(mirror.rows()).toHaveLength(2);
  expect(() => mirror.row(2)).toThrow();
});

test("VolumeMirror count bounds the rows read", () => {
  const buffer = encodeInto(VOL, [
    { volumeId: 1, height: 100 },
    { volumeId: 2, height: 200 },
  ]);
  const mirror = new VolumeMirror(buffer, 1);
  expect(mirror.rows()).toHaveLength(1);
  expect(mirror.row(0).volumeId).toBe(1);
});

test("VolumeMirror rejects a buffer too small for the layout", () => {
  expect(() => new VolumeMirror(new ArrayBuffer(8), 0)).toThrow();
});
