/**
 * @jose/model-types — the generated TypeScript view of the domain MODEL.
 *
 * Everything re-exported here is produced by tooling/codegen from
 * schema/model/unified-model.json. Do not edit files under ./generated by hand;
 * run `bun run codegen` from the repo root instead.
 */
export * from "./generated/index";
